CREATE SCHEMA IF NOT EXISTS `user` DEFAULT CHARACTER SET utf8;

USE `user`;
SHOW TABLES;
DROP TABLE IF EXISTS `user`.`students`;
CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);